### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by zangetsudo** [SkullTech/webdriver-start#1]
i started the brower, but after a few mins, it reported err as bellow:
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed

why ?

**Comment by skulltech** [comment]
I don't think this is related to `webdriver-start`. Most probably the issue is mismatch between the versions of `chromedriver` and your Google Chrome installation. Closing this for now, as it is a very old issue and @zangetsudo probably doesn't need it anymore, nor do I.
